window.BNI_DIRECTORY_DATA = [
  {
    "bio": "",
    "category": "Technology",
    "cellPhone": "914-980-0386",
    "company": "Empire AV LLC",
    "email": "empireav@yahoo.com",
    "logoUrl": "",
    "name": "Charlie Schunk",
    "officePhone": "",
    "profession": "Audio/video solutions",
    "website": "https://www.empireaudiovideo.com"
  },
  {
    "bio": "",
    "category": "Finance",
    "cellPhone": "914-714-9008",
    "company": "Achieve Advisors",
    "email": "cdunn@achieveadvisors.com",
    "logoUrl": "",
    "name": "Christine Dunn, CPA",
    "officePhone": "",
    "profession": "Accounting & advisory services",
    "website": "https://www.achieveadvisors.com"
  },
  {
    "bio": "",
    "category": "Property Services",
    "cellPhone": "914-469-4768",
    "company": "Fresh Coat Painters of White Plains",
    "email": "giovanni@freshcoatpainters.com",
    "logoUrl": "",
    "name": "Giovanni Cosentino",
    "officePhone": "",
    "profession": "Residential & commercial painting",
    "website": "https://freshcoatpainters.com"
  },
  {
    "bio": "James helps individuals, families, and business owners gain clarity and confidence through personalized financial planning. He focuses on retirement, investments, and long-term strategy as a trusted financial partner.",
    "category": "Finance",
    "cellPhone": "516-941-8318",
    "company": "Ameriprise Financial",
    "email": "james.dieguez@ampf.com",
    "logoUrl": "",
    "name": "James M. Dieguez",
    "officePhone": "917-258-3487",
    "profession": "Financial advisor",
    "website": "James Dieguez, Associate Financial Advisor in White Plains, NY"
  },
  {
    "bio": "",
    "category": "Marketing",
    "cellPhone": "",
    "company": "Westchester Retail Network",
    "email": "jeff@westchesterretailnetwork.com",
    "logoUrl": "",
    "name": "Jeff Casper",
    "officePhone": "",
    "profession": "Marketing & advertising services",
    "website": "https://www.westchesterretailnetwork.com"
  },
  {
    "bio": "",
    "category": "Legal",
    "cellPhone": "914-621-2111",
    "company": "Law Offices of Jeffrey A. Asher, PC",
    "email": "kruglinski@asherlawfirm.com",
    "logoUrl": "",
    "name": "Jennifer C. Kruglinski, Esq.",
    "officePhone": "",
    "profession": "Estate planning & litigation attorney",
    "website": "https://www.asherlawfirm.com"
  },
  {
    "bio": "",
    "category": "Property Services",
    "cellPhone": "914-760-3322",
    "company": "Lawn Life Irrigation Specialists",
    "email": "joebeato@msn.com",
    "logoUrl": "",
    "name": "Joe Beato",
    "officePhone": "914-762-6146",
    "profession": "Irrigation & landscape lighting",
    "website": ""
  },
  {
    "bio": "",
    "category": "Property Services",
    "cellPhone": "914-739-4512",
    "company": "F & F Electric Contracting",
    "email": "ffelectriccontractor@gmail.com",
    "logoUrl": "",
    "name": "Joseph Schrade",
    "officePhone": "",
    "profession": "Electrical contractor",
    "website": "https://asher-law.com/asher-law-profile/"
  },
  {
    "bio": "",
    "category": "Finance",
    "cellPhone": "",
    "company": "Albert J. Chapman Agency, Inc.",
    "email": "Lillian@albertjchapman.com",
    "logoUrl": "",
    "name": "Lillian Chapman",
    "officePhone": "914-962-5778 ext. 202",
    "profession": "Insurance services",
    "website": "https://www.albertjchapman.com"
  },
  {
    "bio": "",
    "category": "Property Services",
    "cellPhone": "917-693-8398",
    "company": "RDM Restoration and Move",
    "email": "mark@rdmmove.com",
    "logoUrl": "",
    "name": "Mark Merchant",
    "officePhone": "",
    "profession": "Restoration & moving services",
    "website": "https://www.rdmmove.com"
  },
  {
    "bio": "",
    "category": "Finance",
    "cellPhone": "914-374-6103",
    "company": "New York Life Insurance Company",
    "email": "mrbarone@ft.newyorklife.com",
    "logoUrl": "",
    "name": "Michael R. Barone",
    "officePhone": "914-253-7053",
    "profession": "Risk transfer expert & tax diversification strategist",
    "website": "https://www.newyorklife.com"
  },
  {
    "bio": "",
    "category": "Real Estate",
    "cellPhone": "914-806-8130",
    "company": "North Country Sotheby\u2019s International Realty",
    "email": "paul.leis@northcountrysir.com",
    "logoUrl": "",
    "name": "Paul Leis",
    "officePhone": "914-271-5115",
    "profession": "Associate real estate broker specializing in residential real estate",
    "website": "https://www.sothebysrealty.com/eng/associate/180-a-1208-4023356/paul-leis"
  },
  {
    "bio": "",
    "category": "Property Services",
    "cellPhone": "914-760-7383",
    "company": "Mastercraft Contracting & Remodeling, Inc.",
    "email": "mcpd99@gmail.com",
    "logoUrl": "",
    "name": "Pete Donovan",
    "officePhone": "",
    "profession": "Contracting & remodeling",
    "website": "https://mastercraftcontracting.com/"
  },
  {
    "bio": "",
    "category": "Legal",
    "cellPhone": "914-741-5050",
    "company": "Wolper Law Firm PLLC",
    "email": "rwolper@wolperlaw.com",
    "logoUrl": "",
    "name": "Robert Wolper",
    "officePhone": "",
    "profession": "Real estate, business law & tax reduction",
    "website": "https://www.wolperlaw.com"
  },
  {
    "bio": "Shanthan helps business owners keep their technology running smoothly so they can stay focused on growing their business. He also builds custom automations that save time, reduce manual work, and improve efficiency.",
    "category": "Technology",
    "cellPhone": "203-300-6434",
    "company": "CMIT Solutions of Northern Westchester & Putnam County",
    "email": "subramaniam@cmitsolutions.com",
    "logoUrl": "",
    "name": "Shanthan Subramaniam",
    "officePhone": "203-443-1646",
    "profession": "Managed IT, cybersecurity & custom automation",
    "website": "https://cmitsolutions.com/westchester-ny-1180"
  },
  {
    "bio": "",
    "category": "Finance",
    "cellPhone": "914-621-2111",
    "company": "M&T Bank (Baldwin Place)",
    "email": "sndiaye@mtb.com",
    "logoUrl": "",
    "name": "Sharon NDiaye",
    "officePhone": "646-242-6452",
    "profession": "Senior Relationship Banker",
    "website": "https://www.mtb.com"
  }
];
