window.BNI_DIRECTORY_DATA = [
  {
    "name": "Bob Wolper",
    "profession": "Real estate, business law & tax reduction",
    "company": "Wolper Law Firm PLLC",
    "category": "Legal",
    "bio": "",
    "phone": "914-741-5050",
    "officePhone": "",
    "email": "rwolper@wolperlaw.com",
    "website": "https://www.wolperlaw.com",
    "logoUrl": ""
  },
  {
    "name": "Charlie Schunk",
    "profession": "Audio/video solutions",
    "company": "Empire AV LLC",
    "category": "Technology",
    "bio": "",
    "phone": "914-980-0386",
    "officePhone": "",
    "email": "empireav@yahoo.com",
    "website": "https://www.empireaudiovideo.com",
    "logoUrl": ""
  },
  {
    "name": "Christine Dunn, CPA",
    "profession": "Accounting & advisory services",
    "company": "Achieve Advisors",
    "category": "Finance",
    "bio": "",
    "phone": "914-714-9008",
    "officePhone": "",
    "email": "cdunn@achieveadvisors.com",
    "website": "https://www.achieveadvisors.com",
    "logoUrl": ""
  },
  {
    "name": "Giovanni Cosentino",
    "profession": "Residential & commercial painting",
    "company": "Fresh Coat Painters of White Plains",
    "category": "Property Services",
    "bio": "",
    "phone": "914-469-4768",
    "officePhone": "",
    "email": "giovanni@freshcoatpainters.com",
    "website": "https://freshcoatpainters.com",
    "logoUrl": ""
  },
  {
    "name": "James Dieguez",
    "profession": "Financial advisor",
    "company": "Ameriprise Financial",
    "category": "Finance",
    "bio": "",
    "phone": "917-258-3487",
    "officePhone": "516-941-8318",
    "email": "james.dieguez@ampf.com",
    "website": "https://www.ameriprise.com",
    "logoUrl": ""
  },
  {
    "name": "Jeff Casper",
    "profession": "Marketing & advertising services",
    "company": "Westchester Retail Network",
    "category": "Marketing",
    "bio": "",
    "phone": "",
    "officePhone": "",
    "email": "jeff@westchesterretailnetwork.com",
    "website": "https://www.westchesterretailnetwork.com",
    "logoUrl": ""
  },
  {
    "name": "Jennifer C. Kruglinski, Esq.",
    "profession": "Estate planning & litigation attorney",
    "company": "Law Offices of Jeffrey A. Asher, PC",
    "category": "Legal",
    "bio": "",
    "phone": "914-621-2111",
    "officePhone": "",
    "email": "kruglinski@asherlawfirm.com",
    "website": "https://www.asherlawfirm.com",
    "logoUrl": ""
  },
  {
    "name": "Joe Beato",
    "profession": "Irrigation & landscape lighting",
    "company": "Lawn Life Irrigation Specialists",
    "category": "Property Services",
    "bio": "",
    "phone": "914-760-3322",
    "officePhone": "914-762-6146",
    "email": "joebeato@msn.com",
    "website": "",
    "logoUrl": ""
  },
  {
    "name": "Joseph Schrade",
    "profession": "Electrical contractor",
    "company": "F & F Electric Contracting",
    "category": "Property Services",
    "bio": "",
    "phone": "914-739-4512",
    "officePhone": "",
    "email": "ffelectriccontractor@gmail.com",
    "website": "https://asher-law.com/asher-law-profile/",
    "logoUrl": ""
  },
  {
    "name": "Lillian Chapman",
    "profession": "Insurance services",
    "company": "Albert J. Chapman Agency, Inc.",
    "category": "Finance",
    "bio": "",
    "phone": "914-962-5778 ext. 202",
    "officePhone": "914-962-5778 ext. 202",
    "email": "Lillian@albertjchapman.com",
    "website": "https://www.albertjchapman.com",
    "logoUrl": ""
  },
  {
    "name": "Mark Merchant",
    "profession": "Restoration & moving services",
    "company": "RDM Restoration and Move",
    "category": "Property Services",
    "bio": "",
    "phone": "917-693-8398",
    "officePhone": "",
    "email": "mark@rdmmove.com",
    "website": "https://www.rdmmove.com",
    "logoUrl": ""
  },
  {
    "name": "Michael R. Barone",
    "profession": "Risk transfer expert & tax diversification strategist",
    "company": "New York Life Insurance Company",
    "category": "Finance",
    "bio": "",
    "phone": "914-374-6103",
    "officePhone": "914-253-7053",
    "email": "mrbarone@ft.newyorklife.com",
    "website": "https://www.newyorklife.com",
    "logoUrl": ""
  },
  {
    "name": "Paul Leis",
    "profession": "Residential real estate broker",
    "company": "North Country Sotheby\u2019s International Realty",
    "category": "Real Estate",
    "bio": "",
    "phone": "914-806-8130",
    "officePhone": "914-271-5115",
    "email": "paul.leis@northcountrysir.com",
    "website": "https://www.sothebysrealty.com/eng/associate/180-a-1208-4023356/paul-leis",
    "logoUrl": ""
  },
  {
    "name": "Pete Donovan",
    "profession": "Contracting & remodeling",
    "company": "Mastercraft Contracting & Remodeling, Inc.",
    "category": "Property Services",
    "bio": "",
    "phone": "914-760-7383",
    "officePhone": "",
    "email": "mcpd99@gmail.com",
    "website": "https://mastercraftcontracting.com/",
    "logoUrl": ""
  },
  {
    "name": "Shanthan Subramaniam",
    "profession": "Managed IT, cybersecurity & custom automation",
    "company": "CMIT Solutions of Northern Westchester & Putnam County",
    "category": "Technology",
    "bio": "",
    "phone": "203-443-1646",
    "officePhone": "",
    "email": "subramaniam@cmitsolutions.com",
    "website": "https://cmitsolutions.com/westchester-ny-1180",
    "logoUrl": ""
  },
  {
    "name": "Sharon NDiaye",
    "profession": "Senior Relationship Banker",
    "company": "M&T Bank (Baldwin Place)",
    "category": "Finance",
    "bio": "",
    "phone": "914-621-2111",
    "officePhone": "646-242-6452",
    "email": "sndiaye@mtb.com",
    "website": "https://www.mtb.com",
    "logoUrl": ""
  }
];
